/**/**:
  ros__parameters:
    rate: # [Hz]
      pub_offboard_control_mode: 100.0
      pub_actuator_motors: 500.0
    
    offboard: 
      position: false  # to work with control manager
      velocity: false
      acceleration: false
      attitude: false
      thrust_and_torque: false
      body_rate: false
      direct_actuator: true  # to work with teleop
